global:
  namespace: "ctf-challenges"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  serviceAccount:
    create: true
    automount: true
    annotations: {}

  imagePullSecrets: []

  nodeSelector: {}

  tolerations: []

  affinity: {}
  
  configuration:
    challenge:
      replicaCount: 1
      podAnnotations: {}
      podLabels:
        type: "ctf-challenge"
      podSecurityContext: {}
      securityContext: {}
      volumes: []
      volumeMounts: []
