global:
  namespace: "ctf-challenges"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  serviceAccount:
    create: true
    automount: true
    annotations: {}

  imagePullSecrets: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  gateway:
    enabled: true
    gatewayName: "commons-gateway"
    className: "nginx"
    controllerName: "gateway.nginx.org/nginx-gateway-controller"
  
  configuration:
    challenge:
      replicaCount: 1
      podAnnotations: {}
      podLabels:
        type: "ctf-challenge"
      podSecurityContext: {}
      securityContext: {}
      volumes: []
      volumeMounts: []
