apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  {{- with .Values.global.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.global.autoscaling.enabled }}
  replicas: {{ .Values.global.configuration.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cft-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.global.configuration.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cft-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.global.configuration.api.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "challenge-commons-downloader"
          image: "{{ .Values.downloader.repository }}:{{ .Values.downloader.tag }}"
          imagePullPolicy: {{ .Values.downloader.pullPolicy }}
          {{- if .Values.global.configuration.api.commonsFromHost.enabled }}
          command: 
            - "/bin/sh"
            - "-c"
            - "cp -r /host /mnt"
          {{- else }}
          command: {{ .Values.initCommand | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts: 
            - name: challenge-commons
              mountPath: /mnt
            {{- if .Values.global.configuration.api.commonsFromHost.enabled }}
            - name: commons-host-volume
              readOnly: true
              mountPath: /host
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.global.configuration.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PARENT_CHART_PATH"
              value: {{ .Values.challengeChartPath }}
            - name: "CHALLENGES_NAMESPACE"
              value: {{ .Values.global.challengesNamespace }}
            - name: "GATEWAY_API_NAMESPACE"
              value: {{ .Values.global.gateway.namespace }}
          ports:
            - name: {{ .Values.global.configuration.api.service.name }}
              containerPort: {{ .Values.global.configuration.api.service.targetPort }}
              protocol: TCP
          {{- with .Values.global.configuration.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.configuration.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.configuration.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: challenge-commons
              mountPath: /mnt 
          {{- with .Values.global.configuration.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: challenge-commons
          persistentVolumeClaim:
            claimName: {{ .Values.global.storage.api.claimName }}
        {{- if .Values.global.configuration.api.commonsFromHost.enabled }}
        - name: commons-host-volume
          hostPath:
            path: {{ .Values.global.configuration.api.commonsFromHost.hostPath }}
        {{- end }}
      {{- with .Values.global.configuration.api.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
