{{- range .Values.global.configuration }}
{{- if .configScript }}
{{- range .configScript}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
data:
  configScript.sh: |
{{ .script | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}