global:
  namespace: "k8sctf"
  challengesNamespace: "ctf-challenges"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "default-pod-serviceaccount"

  imagePullSecrets: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  labels:
    application: "k8sctf"
  
  configuration:
    api:
      replicaCount: 1
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      securityContext: {}
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 512Mi

    frontend:
      replicaCount: 1
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      securityContext: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumes: []
      volumeMounts: []

  gateway:
    gatewayName: "commons-gateway"
    className: "nginx"
    controllerName: "gateway.nginx.org/nginx-gateway-controller"
    namespace: "nginx-gateway"

  networkPolicies:
    protectApi:
      name: "api-allow-only-frontend"
      apiLabels:
        app.kubernetes.io/name: ctf-api
      frontendLabels:
        app.kubernetes.io/name: ctf-frontend
      allowedCidr:
        - 127.0.0.1/32
