global:
  namespace: "k8sctf"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "default-pod-serviceaccount"

  imagePullSecrets:
    -name : ""

  nodeSelector: {}

  tolerations: []

  affinity: {}

  labels:
    application: "k8sctf"
  
  configuration:
    api:
      replicaCount: 1
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      securityContext: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumes: []
      volumeMounts: []
      downloader:
        command:
         - "git"
         - "clone"
         - "https://github.com/eskechivoi/k8s-ctf.git"
         - "/app"

    frontend:
      replicaCount: 1
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      securityContext: {}
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumes: []
      volumeMounts: []

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
          serviceName: ctf-api-service
          port: http
        - path: /
          pathType: Prefix
          serviceName: ctf-frontend-service
          port: http
      host: localhost
