global:
  namespace: "k8sctf"
  challengesNamespace: "ctf-challenges"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: "default-pod-serviceaccount"

  imagePullSecrets: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  labels:
    application: "k8sctf"
  
  configuration:
    api:
      enabled: true
      replicaCount: 1
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      securityContext: {}
      commonsFromHost: 
        enabled: true
        hostPath: ""
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 512Mi
      service:
        type: ClusterIP
        port: 80
        targetPort: 8000
        name: http

  gateway:
    enabled: true
    gatewayName: "commons-gateway"
    className: "nginx"
    controllerName: "gateway.nginx.org/nginx-gateway-controller"
    namespace: "nginx-gateway"

  networkPolicies:
    protectApi:
      name: "api-allow-only-frontend"
      apiLabels:
        app.kubernetes.io/name: ctf-api
      allowedCidr:
        - 127.0.0.1/32
