image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable-perl"

selectorLabels:
  component: 'challengeName'

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: http

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

routes:
  className: "nginx"
  annotations: {}
  tls: []
  hosts:
    - host: localhost
  paths:
    - path: /test
      pathType: PathPrefix
      port: 80