image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

selectorLabels:
  component: 'frontend'

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: http

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http