image:
  repository: k8s-ctf-api
  pullPolicy: IfNotPresent
  tag: "0.1.0"

downloader:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "stable"

installerRoleName: helm-installer-role
serviceAccountName: helm-deployer-sa
roleBindingName: helm-installer-binding

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: http

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http