image:
  repository: ctf-api
  pullPolicy: IfNotPresent
  tag: "0.1.0"

challengeCleaner:
  name: "challenge-cleaner"
  schedule: "*/5 * * * *"
  restartPolicy: OnFailure
  image:
    repository: "alpine/helm"
    tag: "3.19"

downloader:
  repository: alpine/git
  pullPolicy: IfNotPresent
  tag: "v2.49.1"

challengeChartPath: "/mnt/challenge-commons"
initCommand:
  - "git"
  - "clone"
  - "https://github.com/eskechivoi/k8s-ctf.git"
  - "/mnt"

installerRoleName: helm-installer-role
serviceAccountName: helm-deployer-sa
roleBindingName: helm-installer-binding

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

routes:
  className: "nginx"
  annotations: {}
  tls: []
  hosts:
    - host: localhost
  paths:
    - path: /api
      pathType: PathPrefix
      serviceName: "ctf-api-service"
      port: 80
    - path: /apidocs
      pathType: PathPrefix
      serviceName: "ctf-api-service"
      port: 80
    - path: /flasgger_static
      pathType: PathPrefix
      serviceName: "ctf-api-service"
      port: 80